### ISSUE TITLE
Doc is outdated / how to run?

### ISSUE THREAD

**Issue by jakub-g** [ziflex/gulp-tasks-monorepo#1]
when I try

```
var MonorepoTasks = require('gulp-tasks-monorepo');
var repo = MonorepoTasks({
  dir: __dirname
});
```

I get

TypeError: MonorepoTasks is not a function

```
$ node
> var MonorepoTasks = require('gulp-tasks-monorepo');
undefined
> MonorepoTasks
{ default: [Function: create] }
```

but in fact I don't know what is the correct call I should do instead of `MonorepoTasks(opts)`?

**Comment by jakub-g** [comment]
Also, how do I invoke the thing from command line

i.e. with this code 

```
    var gulp = require('gulp');
    var MonorepoTasks = require('gulp-tasks-monorepo');

    var repo = MonorepoTasks({
        dir: path.join(__dirname, '/packages')
    });

    repo.task('clean', function clean(pkg, done) {
        gutil.log('Cleaning', pkg.name(), 'package');

        del(path.join(pkg.location(), '/dist'), done);
    });
```

should I run `gulp clean` or what command to execute `clean` on all packages? It's not really clear

**Comment by ziflex** [comment]
@jakub-g hey, thanks for this issue!
The module was written in ES6 and exported as ES6 module and since you are using plain ````require```` function you were getting a module object with ````default```` property which you would have to call.
I published fix for that, so now the module exported as commonjs module.

Regarding other questions, you should be able to run ````gulp TASK_NAME````, you don't have to import gulp, the module will import it automatically.

Once you initialized the instance of the ````monorepo```` with a folder path where you packages are located, you can treat it as a gulp instance.

Let me know if you are still experiencing the issues.
